"// rotina de avaliação estática\n"
                + "// recebe o número do caso de teste e o diretório onde os dados\n"
                + "// de execução do caso de teste são salvos\n"
                + "\n"
                + "int __avaliacaoEstatica(int ct, char* dirct, char* dirctresp) {\n"
                + "\n"
                + "     // abrir arquivo de gabarito e entrada (caso necessário)\n"
                + "     char caminho[4097];\n"
                + "     sprintf(caminho, \"%s/gabarito.txt\", dirct);\n"
                + "     FILE* fg = fopen(caminho, \"r\");\n"
                + "     //sprintf(caminho, \"%s/entrada.txt\", dirct);\n"
                + "     //FILE* fe = fopen(caminho, \"r\");\n"
                + "\n"
                + "         //carregar gabarito (e entrada)\n"
                + "\n"
                + "     fclose(fg);\n"
                + "     //fclose(fe);\n"
                + "\n"
                + "     // abrir arquivo de saída\n"
                + "     sprintf(caminho, \"%s/saida.txt\", dirctresp);\n"
                + "     FILE* fs = fopen(caminho, \"r\");\n"
                + "\n"
                + "         //carregar saída da resposta submetida\n"
                + "\n"
                + "     // avaliar saída com relação ao gabarito\n"
                + "\n"
                + "}"