"// esta rotina será executada antes de cada caso de teste\n"
                + "// do programa submetido, carregando valores para as\n"
                + "// variáveis globais, seja a partir dos dados gerados em arquivo,\n"
                + "// seja gerando dados em tempo de execução"
                + "\n"
                + "\n"
                + "int __carregar_dados_casoteste(int ct, char* dirct) {\n"
                + "  // a variável 'dirct' é o caminho até o diretório onde ficam os\n"
                + "  // os arquivos referentes aos casos de teste (entrada.fb, gabarito.fb, etc.)\n"
                + "  // acesse esses arquivos no modo 'readonly'\n"
                + "  \n"
                + "     // abrir arquivo com entradas"
                + "     char caminho[4097];\n"
                + "     sprintf(caminho, \"%s/entrada.txt\", dirct);\n"
                + "     FILE* f = fopen(caminho, \"r\");\n"
                + "     \n"
                + "         // carregar dados de entrada\n"
                + "     \n"
                + "     fclose(f);\n"
                + "     \n"
                + "}"