"// inicializa a semente randômica\n"
                + "#include <sys/time.h>\n"
                + "void iniRand() {\n"
                + "  struct timeval time;\n"
                + "  gettimeofday(&time,NULL);\n"
                + "  srand((time.tv_sec * 1000) + (time.tv_usec / 1000));\n"
                + "  \n"
                + "}\n"
                + "\n"
                + "// gerar e carregar valores de variáveis globais de entrada e inicializar outras variáveis globais\n"
                + "int gerarCasoTeste(int ct) {\n"
                + "  \n"
                + "}\n"
                + "\n"