"// gerar os arquivos (dados estáticos) de caso de teste\n"
                + "int gerarArquivosCasoTeste(int ct, char* dirct) {\n"
                + "  // a variável 'dirct' é o caminho até o diretório onde ficam os\n"
                + "  // os arquivos referentes ao caso de teste (entrada.fb, gabarito.fb)\n"
                + "  // você pode colocar qualquer outro arquivo que queira nesse diretório\n"
                + "  \n"
                + "    // gerar valores de entrada\n"
                + "    gerarCasoTeste(ct);\n"
                + "\n"
                + "    // salvar entrada\n"
                + "    char caminho[4097];\n"
  	            + "    sprintf(caminho, \"%s/entrada.txt\", dirct);\n"
  	            + "    FILE* f = fopen(caminho, \"w\");\n"
                + "\n"
                + "         // gravar entrada\n"
                + "\n"
                + "    fclose(f);\n"
                + "\n"
                + "    // calcular solução\n"
                + "    solucaoTarefa();\n"
                + "\n"
                + "    // salvar gabarito\n"
                + "    sprintf(caminho, \"%s/gabarito.txt\", dirct);\n"
                + "    f = fopen(caminho, \"w\");\n"
                + "\n"
                + "         // gravar gabarito\n"
                + "\n"
                + "\n  fclose(f);\n"
                + "}"