"// esta rotina será executada ao final de cada caso de teste\n"
                + "// do programa submetido para salvar a resposta em arquivo\n"
                + "// a variável dirctresp é o diretório onde a saída do caso de teste\n"
                + "// gerada pelo programa submetido é armazenada\n"
                + "\n"
                + "int __salvar_saida_casoteste(int ct, char* dirctresp) {\n"
                + "  // a variável 'dirctresp' é o caminho até o diretório do caso de teste\n"
                + "  // onde os dados gerados pelo caso de teste do programa submetido\n"
                + "  // são guardados (saida.fb)\n"
                + "\n"
                + "     //abrir arquivo de saída\n"
                + "     char caminho[4097];"
                + "     sprintf(caminho, \"%s/saida.txt\", dirctresp);\n"
                + "     FILE* f = fopen(caminho, \"w\");\n"
                + "\n"
                + "         // gravar dados de saída"
                + "\n"
                + "     fclose(f);\n"
                + "}"